name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOSY}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
              cd ..
              cd var/www/html
              git clone git@github.com/SammyDeAgent/cytokine-osmium.git
              echo "Deploy to Digital Ocean Droplet successful."

